### ISSUE TITLE
`-d` option: create the directory if it doesn't exist. 

### ISSUE THREAD

**Issue by smirarab** [maryamrabiee/SODA#4]

**Comment by heather340** [comment]
Hi! I'm running this for the first time, and the -d option is still giving me trouble. 

```
(species2021) bash-4.2$ pwd 
/fs/scratch/UCE/taxon-sets/all/soda
```

```
(species2021) bash-4.2$ ls
75_out  astral.all.75.tre  treeshr.astral_75.tre
```

```
(species2021) bash-4.2$ python3 /users/bin/SODA/run_delimitation.py -i treeshr.astral_75.tre \
> -d 75_out -o soda_all_75 -t astral.all.75.tre
Launching SODA1.0.1
236
==========================Running java -Xmx1200m -jar ./Astral/astral.5.7.3.jar -i treeshr.astral_75.tre -o 75_out/astral.out -t 10 -q astral.all.75.tre=========================
==========================ASTRAL run finished=======================
Traceback (most recent call last):
  File "/users/bin/SODA/run_delimitation.py", line 97, in <module>
    tree = run_astral(gene_trees_path, n, len(lines), out_dir+"/astral.out", mapping ,guide_tree)
  File "/users/bin/SODA/run_delimitation.py", line 42, in run_astral
    file=open(out, "r"),
FileNotFoundError: [Errno 2] No such file or directory: '75_out/astral.out'
```

Any ideas would be welcome!
Thanks, 
Heather
