### ISSUE TITLE
Error while running SODA

### ISSUE THREAD

**Issue by josh3397** [maryamrabiee/SODA#7]
Hello,

I'm trying to run SODA program on my dataset. I have a set of gene trees in a single file called loci.treefile. I get following error when I run it
Traceback (most recent call last):
  File "run_delimitation.py", line 110, in <module>
    tree = run_astral(gene_trees_path, n, len(lines), out_dir+"/astral.out", mapping ,guide_tree, astral_dir)
  File "run_delimitation.py", line 22, in run_astral
    bashCommand = "java -Xmx"+ str(100 * ceil(log(n * g, 10)* log(n, 10)))+"m -jar "+ latest_file +" -i " + gene_trees + " -o "+ out + " -t 10"
TypeError: can only concatenate str (not "int") to str

Would greatly appreciate your help in solving this! 

Regards,
Mukta

**Comment by josh3397** [comment]
I'm also getting the following error:
ValueError: max() arg is an empty sequence

Does this error has something to do with the python version? I can't think of any other reasons. As I'm running this on sample data, it't not even the data issue. 

Any help would be appreciated

**Comment by paigemaroni** [comment]
Hi there,

I have also received the same errors and would love to know how to solve these issues.

Especially the following:
ValueError: max() arg is an empty sequence

Many thanks,
Paige

**Comment by maryamrabiee** [comment]
For the max() arg error, please provide the Astral directory with -j, or use the updated code.

**Comment by paigemaroni** [comment]
Hi there, 

Thank you for your above help.

Specifying the ASTRAL directory has helped but now there seems to be an issue with the "guide tree". In my case, I am not specifying one. 

My command: python3.9 run_delimitation.py -i soda-trial/gene_trees.tree -d output/ -o SODAsp-delim.txt -j Astral/

Traceback (most recent call last):
  File "../SODA-master-2/run_delimitation.py", line 120, in <module>
    tree = root_guide_tree(gene_trees_path, n, len(lines), out_dir+"/astral.out", None , tree, astral_dir)
  File "../SODA-master-2/run_delimitation.py", line 61, in root_guide_tree
    min_p = min(p_vals, key = lambda x: x[0])
ValueError: min() arg is an empty sequence

Many thanks!

**Comment by paigemaroni** [comment]
Hey there Maryam, Thank you very much – this error is no longer! I did however receive a new error that looks like it may require a similar fix? I wondered, what your thoughts on this were? My error message is below: Specifying the ASTRAL directory has helped but now there seems to be an issue with the "guide tree". In my case, I am not specifying one.My command: python3.9 run_delimitation.py -i soda-trial/gene_trees.tree -d output/ -o SODAsp-delim.txt -j Astral/Traceback (most recent call last):File "../SODA-master-2/run_delimitation.py", line 120, intree = root_guide_tree(gene_trees_path, n, len(lines), out_dir+"/astral.out", None , tree, astral_dir)File "../SODA-master-2/run_delimitation.py", line 61, in root_guide_treemin_p = min(p_vals, key = lambda x: x[0])ValueError: min() arg is an empty sequenceMany thanks!Thank you so much for your help, advice and time. I think SODA is going to be an incredibly useful tool!Sincerely,Paige   From: maryamrabieeSent: Monday, 14 March 2022 6:05 PMTo: maryamrabiee/SODACc: paigemaroni; CommentSubject: Re: [maryamrabiee/SODA] Error while running SODA (Issue #7) For the max() arg error, please provide the Astral directory with -j, or use the updated code.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>
